# =============================================================================
# CargoTrack — Terraform State Backend Bootstrap
#
# PURPOSE:
#   Creates the S3 bucket and DynamoDB table that the main environments/dev
#   workspace uses as its remote state backend.
#
# DAILY RE-CREATION (after admin cleanup):
#   Since this directory uses LOCAL state (terraform.tfstate in this folder),
#   and the admin wipes all AWS resources daily, you must remove stale state
#   before each morning's re-apply:
#
#     cd cargotrack-infra/bootstrap
#     Remove-Item -ErrorAction SilentlyContinue terraform.tfstate, terraform.tfstate.backup
#     terraform apply -auto-approve
#
#   After bootstrap succeeds, proceed to environments/dev:
#     terraform init -reconfigure
#     terraform apply
#
# NOTE: force_destroy = true on the S3 bucket allows re-creation without
#   manual bucket emptying in case of partial state. Safe for a state bucket
#   because state is re-generated by terraform apply anyway.
# =============================================================================

locals {
  tags = {
    Project     = var.project_name
    ManagedBy   = "Terraform"
    Purpose     = "Terraform remote state backend"
    Environment = "bootstrap"
  }
}

resource "aws_s3_bucket" "state" {
  bucket        = "${var.project_name}-terraform-state"
  force_destroy = true   # Safe for state bucket — state is regenerated on apply

  tags = merge(local.tags, { Name = "${var.project_name}-terraform-state" })
}

resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "state" {
  bucket = aws_s3_bucket.state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_dynamodb_table" "locks" {
  name         = "${var.project_name}-terraform-locks"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }

  tags = merge(local.tags, { Name = "${var.project_name}-terraform-locks" })
}
